name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  
jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: "AKIAYP627HMBS6QXMFHK"
          aws-secret-access-key: "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"
          aws-region: ap-south-1
      -
        name: Login to Amazon public ECR
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public
      -
        name: Build and push images
        run: |
          ./scripts/build-frontend.sh
          ./scripts/build-api.sh
          ./scripts/push-frontend.sh
          ./scripts/push-api.sh

  deploy-to-aws:
    runs-on: ubuntu-latest
    needs: build-and-push-images
    steps:
      -
        name: Deploy the app
        run: |
            aws deploy create-deployment \
            --application-name sampledeploy \
            --deployment-group-name helloworld \
            --s3-location bucket=sampletext1221.bucket,key=code-deploy-docker-compose.zip,bundleType=zip
        env:
          aws-access-key-id: "AKIAYP627HMBS6QXMFHK"
          aws-secret-access-key: "uk+pGLXd7qUovIHjCbHJHxLe4OeERY+lcqbYJn5y"
          aws-region: ap-south-1

  
